### PR TITLE
Add conversion utility

### LINKED ISSUE #46: Conversion utility
Hi,

I have started using this gem to generate SVGs for CNC milling and one of the use cases I have is using an existing SVG as a starting point for the generation of the desired SVG. I created a utility that takes an SVG as input and converts it to a `victor` script. Is this something you think could be included in the gem?

Script is below:

```ruby
require "nokogiri"
require "stringio"
require "byebug"

input = ARGF
doc = Nokogiri::XML(input)

svg = doc.children.last
raise "not an SVG" if svg.name != "svg"

RAW_NODES = ["text", "style"]

def get_attrs(node)
  node.attributes.values.reduce({}) do |acc, attr|
    name = attr.name
    value = attr.value
    key = attr.respond_to?(:prefix) ? "#{attr.prefix}:#{name}" : name
    acc[key] = value
    acc
  end
end

def process_node(node, out)
  children = node.children
  unless children.empty?
    out.puts "do"
    process_nodes(children, out)
    out.puts "end"
  end
end

def process_nodes(nodes, out)
  nodes.each do |node|
    attrs = get_attrs(node)
    output = true
    params = attrs.empty? ? "" : "(#{attrs.inspect})"
    name = node.name
    if RAW_NODES.include?(name)
      inner_text = node.text
      output = inner_text.strip.length > 0
      params = " #{inner_text.inspect}"
    end
    if output
      out.write "#{node.name}#{params} "
      process_node(node, out) unless RAW_NODES.include?(name)
      out.puts
    end
  end
end

result = StringIO.new
result.puts 'require "victor"'
result.puts
result.write "svg = Victor::SVG.new( "
result.write get_attrs(svg).inspect
result.puts ")"
result.puts "svg.build do"
process_nodes(svg.children, result)
result.puts "end"
result.puts 'svg.save "convert_test"'
result.rewind
str = result.read

puts str.gsub("=>", ":")

```

Usage is: `ruby convert.rb [svg_filename]`. To get improved formatting I pipe it through the `rufo` formatter.

### PR DESCRIPTION
**Pull request by gingermusketeer**
Resolves #46

Todo: 
- [ ] Add CLI to interface with the parser and code generator.

@DannyBen Let me know if you think this is heading in the right direction :)

### CODE REVIEW

**Comment by DannyBen** [comment]
Looks nice. I wonder if this should be built in or a separate gem.
Especially if we want to add a CLI, we can do one easily with [mister_bin](https://github.com/dannyben/mister_bin) which is my go-to library for CLIs.

**Comment by gingermusketeer** [comment]
@DannyBen I am having a little trouble with `mister_bin`. There seems to be an issue with what is being passed into docopt. When argv is `["spec/fixtures/pacman.svg"]` the command works but `["convert", "spec/fixtures/pacman.svg"] is what is getting passed in.

Any idea what I am doing wrong?

**Comment by DannyBen** [comment]
I didn't know you already started - I didn't mean to dump it all on you, I wanted us to work together on this :)

If you already started, where is the repo with your attempts, so I can clone and offer help?

**Comment by DannyBen** [comment]
@gingermusketeer - I invited you to a new repo: https://github.com/DannyBen/victor-cli

Lets work there, as I prefer not to add CLI directly to Victor, and not to add additional dependencies, such as nokogiri.,

I started a base gem in that other repo, set up with mister_bin and ready to accept your code for the parser and all. Just don't push to master, as I protected this branch.

Also a few more things I noticed in your original code that I would love to enhance:

1. The generated code was not indented at all, we will need to handle it
2. All the generated hashes were not classic ruby (they were not properly formatted, and used string keys
3. I prefer "Seattle style" ruby - less () 
4. For the specs, I prefer avoiding long strings as the `subject` or expected output, and I usually do a heavy use or `rspec_fixtures` for that, which is showing you interactively the output, and you "approve" or "reject".

We can work on all that together, I just need to understand we are on the same page.

**Comment by DannyBen** [comment]
Closed in favor of https://github.com/DannyBen/victor-cli

**Pull request closed without merging**
